version: '3.7'

networks:
  sella:
    name: sellanet
    external: true

services:
  app:
    build:
      args:
        user: test
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: sella
    container_name: sella-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    environment:
      DB_DSN: $DB_DSN
      DB_HOST: $DB_HOST
      DB_USER: $DB_USERNAME
      DB_NAME: $DB_DATABASE
      DB_PASSWORD: $DB_PASSWORD
      DB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      DB_PORT: $DB_PORT
    networks:
      sella:
        ipv4_address: 182.30.0.12

  nginx:
    image: nginx:alpine
    container_name: sella-nginx
    restart: unless-stopped
    ports:
      - $WEB_PORT:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      sella:
        ipv4_address: 182.30.0.13